### ISSUE TITLE
unable to load a module using a variable

### ISSUE THREAD

**Issue by jlberrocal** [anywhichway/node-require#1]
I'm working in a angular2 project which needs to load some components in a totally dynamic way, that means that i will need to search into a folder and then a module according with a variable value, however actually i'm not able to achieve that, because when i use the variable node-require lost it's context and try to load '.' which obviously don't have sense for my application.

There is any workaround for deal with something like my problem?

Thanks in advance.

**Comment by anywhichway** [comment]
Can  you post a snippet of code that shows what you are trying to do?

**Comment by jlberrocal** [comment]
Ok basically I need to import an angular  component on the fly. 

In more simple words I will ask the server for some information and in that information comes which is the component that I need... I will try to post a plunkr at night (GMT-6)
